[package]
name = "rust-workspace-test"
version = "0.0.1"
edition = "2025"
description = "Rust development environment setup demo project"
authors = ["Rust Bootcamp, Jeni Rainer"]
license = "MIT"

[dependencies]
rand = "0.8"